import type { Agent } from "@/lib/types/atlas";

export const agents: Agent[] = [
  {
    id: "atlas",
    name: "Atlas",
    title: "Right-Hand Man / Chief of Staff",
    buildingId: "keep-hall",
    role: "Summarizes the whole system, proposes next actions, and coordinates agents.",
    status: "thinking",
    currentTask: "Preparing the overnight village briefing.",
    modelTier: "flagship",
    toolPolicy: "Read broadly; propose freely; never post, spend, send, invest, or merge.",
    riskLevel: "medium",
  },
  {
    id: "nova",
    name: "Nova",
    title: "Content Studio Manager",
    buildingId: "content-studio",
    role: "Drafts hooks, scripts, content ideas, captions, and calendars.",
    status: "waiting_approval",
    currentTask: "Waiting on human review for 5 AI productivity hooks.",
    modelTier: "workhorse",
    toolPolicy: "Draft-only; all publishing routes to Approval Court.",
    riskLevel: "medium",
  },
  {
    id: "vera",
    name: "Vera",
    title: "Product Workshop Manager",
    buildingId: "product-workshop",
    role: "Researches digital products, templates, dashboards, and product experiments.",
    status: "working",
    currentTask: "Comparing three finance template opportunities.",
    modelTier: "workhorse",
    toolPolicy: "Research and draft listings; no marketplace publishing.",
    riskLevel: "medium",
  },
  {
    id: "forge",
    name: "Forge",
    title: "Freelance Guild Manager",
    buildingId: "freelance-guild",
    role: "Drafts proposals, evaluates service ideas, and tracks gig opportunities.",
    status: "waiting_approval",
    currentTask: "Proposal draft ready for a dashboard automation gig.",
    modelTier: "workhorse",
    toolPolicy: "Draft-only; no automated outreach or platform messaging.",
    riskLevel: "high",
  },
  {
    id: "ledger",
    name: "Ledger",
    title: "Treasury Manager",
    buildingId: "treasury",
    role: "Tracks revenue, costs, profit, AI spend, hosting spend, and ROI.",
    status: "working",
    currentTask: "Reconciling local cost events and budget caps.",
    modelTier: "cheap",
    toolPolicy: "Narrative analysis only; numbers come from ledger calculations.",
    riskLevel: "low",
  },
  {
    id: "quill",
    name: "Quill",
    title: "Research Librarian",
    buildingId: "research-library",
    role: "Stores research, notes, citations, summaries, and agent outputs.",
    status: "idle",
    currentTask: "Standing by to index new outputs.",
    modelTier: "cheap",
    toolPolicy: "Read/write local notes; no external publishing.",
    riskLevel: "low",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    title: "Approval Court Clerk",
    buildingId: "approval-court",
    role: "Reviews risky actions and routes them for human approval.",
    status: "waiting_approval",
    currentTask: "Holding five tier-3 actions for review.",
    modelTier: "none",
    toolPolicy: "Gatekeeper only; approval state is human-controlled.",
    riskLevel: "critical",
  },
  {
    id: "architect",
    name: "Architect",
    title: "Engineering Workshop Manager",
    buildingId: "engineering-workshop",
    role: "Proposes UI, code, building, and system upgrades.",
    status: "working",
    currentTask: "Drafting a village status mini-map upgrade proposal.",
    modelTier: "flagship",
    toolPolicy: "Draft branches and PR summaries later; no direct production writes.",
    riskLevel: "medium",
  },
  {
    id: "allocator",
    name: "Allocator",
    title: "Atlas Allocation Analyst",
    buildingId: "allocation-tower",
    role: "Future ETF allocation and business resource decision-support agent.",
    status: "working",
    currentTask: "Running a mock paper ETF allocation review.",
    modelTier: "flagship",
    toolPolicy: "Display-only and paper mode; no live orders or paid advice.",
    riskLevel: "critical",
  },
];
