import type { Building } from "@/lib/types/atlas";

export const buildings: Building[] = [
  {
    id: "keep-hall",
    name: "Keep Hall / HQ",
    shortName: "Keep Hall",
    category: "core",
    description:
      "Home of Atlas, the Right-Hand Man agent, and the command briefing for the whole village.",
    visual: "Banner-topped great hall with lit windows and a hilltop command table.",
    managerAgentId: "atlas",
    status: "working",
    position: { x: -40, y: -150 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 7.42,
    roi: -1,
    riskLevel: "medium",
    tools: ["Read-only village summaries", "Decision log", "GitHub proposal drafts"],
    metrics: ["Open decisions", "Blocked tasks", "Pending proposals"],
    recommendedAction: "Review the overnight briefing and clear the Approval Court first.",
    pendingApprovalIds: [],
    taskIds: ["task-atlas-briefing"],
  },
  {
    id: "treasury",
    name: "Treasury",
    shortName: "Treasury",
    category: "core",
    description:
      "The financial truth layer: cash, cost events, revenue events, budget caps, and ROI by experiment.",
    visual: "Vault-fronted counting house with glowing ledgers and coin trays.",
    managerAgentId: "ledger",
    status: "working",
    position: { x: -250, y: -25 },
    level: 1,
    revenueMTD: 88,
    expensesMTD: 31.39,
    roi: 1.8,
    riskLevel: "low",
    tools: ["Local ledger", "Budget caps", "Future Stripe read webhook"],
    metrics: ["Revenue MTD", "AI spend", "ROI per experiment"],
    recommendedAction: "Keep the monthly AI spend under 70% of budget until real revenue repeats.",
    pendingApprovalIds: [],
    taskIds: ["task-ledger-ai-spend"],
  },
  {
    id: "content-studio",
    name: "Content Studio",
    shortName: "Studio",
    category: "revenue",
    description:
      "Drafts original hooks, scripts, captions, calendars, and content experiments for human review.",
    visual: "Neon-lit atelier with quills, cameras, and a content calendar wall.",
    managerAgentId: "nova",
    status: "waiting_approval",
    position: { x: 245, y: -55 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 4.84,
    roi: -1,
    riskLevel: "medium",
    tools: ["Draft generation", "Brand voice notes", "Approval Court routing"],
    metrics: ["Drafts created", "Publish approvals", "Engagement once connected"],
    recommendedAction: "Approve, revise, or reject Nova's first content draft before creating more.",
    pendingApprovalIds: ["approval-content-publish"],
    taskIds: ["task-nova-hooks", "task-sentinel-content"],
  },
  {
    id: "product-workshop",
    name: "Product Workshop",
    shortName: "Workshop",
    category: "revenue",
    description:
      "Researches and drafts digital products such as templates, dashboards, and small experiments.",
    visual: "Maker workshop packed with blueprints, shelves, and glowing product mockups.",
    managerAgentId: "vera",
    status: "working",
    position: { x: -72, y: 132 },
    level: 1,
    revenueMTD: 88,
    expensesMTD: 9.1,
    roi: 8.67,
    riskLevel: "medium",
    tools: ["Niche research", "Template drafts", "Listing draft previews"],
    metrics: ["Ideas found", "Products built", "Revenue per listing"],
    recommendedAction: "Pick one finance/data template idea and turn it into a shippable artifact.",
    pendingApprovalIds: ["approval-product-listing"],
    taskIds: ["task-vera-products"],
  },
  {
    id: "freelance-guild",
    name: "Freelance Guild",
    shortName: "Guild",
    category: "revenue",
    description:
      "Surfaces data and dashboard gigs, drafts proposals, and tracks the pipeline without sending messages.",
    visual: "Guild hall with job boards, contract scrolls, and a warm negotiation table.",
    managerAgentId: "forge",
    status: "waiting_approval",
    position: { x: -320, y: 120 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 2.12,
    roi: -1,
    riskLevel: "high",
    tools: ["Read-only gig research", "Proposal drafts", "Manual outreach checklist"],
    metrics: ["Proposal drafts", "Win rate", "Revenue per hour"],
    recommendedAction: "Review Forge's proposal draft manually; never mass-send platform messages.",
    pendingApprovalIds: ["approval-freelance-send"],
    taskIds: ["task-forge-proposal"],
  },
  {
    id: "engineering-workshop",
    name: "Engineering Workshop",
    shortName: "Engineering",
    category: "support",
    description:
      "Home of proposed code, UI, building, and tool upgrades routed through branch, PR, tests, and preview.",
    visual: "Spark-lit forge with scaffolding, workbenches, and blueprint rails.",
    managerAgentId: "architect",
    status: "upgrading",
    position: { x: 340, y: 70 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 11.2,
    roi: -1,
    riskLevel: "medium",
    tools: ["Local code proposals", "Mock PR queue", "Build health checks"],
    metrics: ["Proposed upgrades", "Build status", "PR readiness"],
    recommendedAction: "Keep code proposals in drafts until tests and a human merge gate exist.",
    pendingApprovalIds: ["approval-engineering-ui"],
    taskIds: ["task-architect-upgrade"],
  },
  {
    id: "approval-court",
    name: "Approval Court",
    shortName: "Court",
    category: "core",
    description:
      "The required human gate for posting, sending, spending, publishing, code changes, and investing.",
    visual: "Courthouse with amber lanterns and a docket board of pending cases.",
    managerAgentId: "sentinel",
    status: "waiting_approval",
    position: { x: 78, y: 40 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 0.84,
    roi: -1,
    riskLevel: "critical",
    tools: ["Approval previews", "Reject/revise queue", "Future audit log"],
    metrics: ["Pending approvals", "Aged approvals", "Risk exposure"],
    recommendedAction: "Resolve high-risk approvals before allowing new external-facing drafts.",
    pendingApprovalIds: [
      "approval-content-publish",
      "approval-product-listing",
      "approval-freelance-send",
      "approval-engineering-ui",
      "approval-investment-manual",
    ],
    taskIds: ["task-sentinel-content"],
  },
  {
    id: "research-library",
    name: "Research Library",
    shortName: "Library",
    category: "support",
    description:
      "Stores research notes, citations, agent outputs, decisions, and future retrieval memory.",
    visual: "Tall archive with floating books, index crystals, and quiet reading lamps.",
    managerAgentId: "quill",
    status: "idle",
    position: { x: -198, y: 235 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 1.18,
    roi: -1,
    riskLevel: "low",
    tools: ["Local notes", "Research summaries", "Future vector memory"],
    metrics: ["Notes indexed", "Research outputs", "Duplicate ideas removed"],
    recommendedAction: "Consolidate current research before running another broad trend pass.",
    pendingApprovalIds: [],
    taskIds: ["task-quill-organize"],
  },
  {
    id: "allocation-tower",
    name: "Atlas Treasury / Allocation Tower",
    shortName: "Allocator",
    category: "future",
    description:
      "Paper-mode decision support for the future Atlas Allocation quant service and business resource weighting.",
    visual: "Observatory tower with ETF orbits, paper-trading charts, and a locked real-money gate.",
    managerAgentId: "allocator",
    status: "working",
    position: { x: 235, y: 225 },
    level: 1,
    revenueMTD: 0,
    expensesMTD: 3.19,
    roi: -1,
    riskLevel: "critical",
    tools: ["Mock ETF allocation", "Paper-mode dashboard", "Manual review prompts"],
    metrics: ["Sharpe mock", "Drawdown mock", "Business resource weights"],
    recommendedAction: "Keep all allocation output as decision-support and paper mode only.",
    pendingApprovalIds: ["approval-investment-manual"],
    taskIds: ["task-allocator-review"],
  },
];
