import type { Task, TaskRun } from "@/lib/types/atlas";

export const tasks: Task[] = [
  {
    id: "task-nova-hooks",
    title: "Draft 5 TikTok hooks for AI productivity content",
    buildingId: "content-studio",
    agentId: "nova",
    status: "waiting_approval",
    summary: "Five original short-form hooks are drafted and queued for human review.",
    costEstimate: 0.08,
    expectedValue: "Seed content-to-product funnel without auto-posting.",
    createdAt: "2026-06-25T00:40:00-07:00",
    updatedAt: "2026-06-25T01:10:00-07:00",
  },
  {
    id: "task-vera-products",
    title: "Research 3 digital product ideas",
    buildingId: "product-workshop",
    agentId: "vera",
    status: "running",
    summary: "Comparing a cash-flow sheet, ETF explainer dashboard, and OPT timeline tracker.",
    costEstimate: 0.16,
    expectedValue: "Find one small product with a clear buyer and low platform risk.",
    createdAt: "2026-06-25T00:45:00-07:00",
    updatedAt: "2026-06-25T01:20:00-07:00",
  },
  {
    id: "task-ledger-ai-spend",
    title: "Calculate monthly AI spend",
    buildingId: "treasury",
    agentId: "ledger",
    status: "completed",
    summary: "Local cost events total $14.13 in AI spend MTD, below the mock budget threshold.",
    costEstimate: 0,
    expectedValue: "Keeps the most important risk visible in the HUD.",
    createdAt: "2026-06-25T00:20:00-07:00",
    updatedAt: "2026-06-25T00:22:00-07:00",
  },
  {
    id: "task-sentinel-content",
    title: "Wait for approval on a content draft",
    buildingId: "approval-court",
    agentId: "sentinel",
    status: "waiting_approval",
    summary: "Publishing is blocked until the user approves, rejects, or requests revision.",
    costEstimate: 0,
    expectedValue: "Prevents accidental public posting.",
    createdAt: "2026-06-25T01:11:00-07:00",
    updatedAt: "2026-06-25T01:11:00-07:00",
  },
  {
    id: "task-architect-upgrade",
    title: "Propose a new building upgrade",
    buildingId: "engineering-workshop",
    agentId: "architect",
    status: "queued",
    summary: "Mock plan for a Mission Control board and build-health rail.",
    costEstimate: 0.34,
    expectedValue: "Improves operator visibility once real workers exist.",
    createdAt: "2026-06-25T01:05:00-07:00",
    updatedAt: "2026-06-25T01:06:00-07:00",
  },
  {
    id: "task-allocator-review",
    title: "Run a paper ETF allocation review",
    buildingId: "allocation-tower",
    agentId: "allocator",
    status: "running",
    summary: "Mock paper-mode allocation compares VTI, VXUS, BND, and SGOV.",
    costEstimate: 0.22,
    expectedValue: "Exercises future Atlas display patterns without real trades.",
    createdAt: "2026-06-25T00:55:00-07:00",
    updatedAt: "2026-06-25T01:25:00-07:00",
  },
  {
    id: "task-forge-proposal",
    title: "Draft a freelance dashboard proposal",
    buildingId: "freelance-guild",
    agentId: "forge",
    status: "waiting_approval",
    summary: "Proposal draft for a small analytics dashboard job is ready for manual sending.",
    costEstimate: 0.11,
    expectedValue: "Fastest path to a real revenue event if manually approved.",
    createdAt: "2026-06-25T00:50:00-07:00",
    updatedAt: "2026-06-25T01:19:00-07:00",
  },
  {
    id: "task-atlas-briefing",
    title: "Summarize the village's overnight status",
    buildingId: "keep-hall",
    agentId: "atlas",
    status: "running",
    summary: "Atlas is preparing a cross-building snapshot with blockers and next actions.",
    costEstimate: 0.42,
    expectedValue: "Converts noisy operations into a short daily operating brief.",
    createdAt: "2026-06-25T01:00:00-07:00",
    updatedAt: "2026-06-25T01:21:00-07:00",
  },
  {
    id: "task-quill-organize",
    title: "Organize research notes from Content Studio",
    buildingId: "research-library",
    agentId: "quill",
    status: "queued",
    summary: "Tag and store the latest content and product research outputs.",
    costEstimate: 0.03,
    expectedValue: "Improves future retrieval and reduces repeated research.",
    createdAt: "2026-06-25T01:22:00-07:00",
    updatedAt: "2026-06-25T01:22:00-07:00",
  },
];

export const taskRuns: TaskRun[] = [
  {
    id: "run-001",
    taskId: "task-ledger-ai-spend",
    status: "completed",
    startedAt: "2026-06-25T00:20:00-07:00",
    endedAt: "2026-06-25T00:22:00-07:00",
    cost: 0,
    resultPreview: "AI spend is $14.13 MTD across 23 local mock cost events.",
  },
  {
    id: "run-002",
    taskId: "task-nova-hooks",
    status: "waiting_approval",
    startedAt: "2026-06-25T00:40:00-07:00",
    endedAt: "2026-06-25T01:10:00-07:00",
    cost: 0.08,
    resultPreview: "Drafted 5 short hooks. No posting action was taken.",
  },
  {
    id: "run-003",
    taskId: "task-allocator-review",
    status: "running",
    startedAt: "2026-06-25T00:55:00-07:00",
    cost: 0.22,
    resultPreview: "Paper-mode allocation run in progress.",
  },
];
